name: Wpm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in
        uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: 'Login in to ACR'
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Get current date in yymmdd format
        run: echo "DATE=$(date +'%y%m%d')" >> $GITHUB_ENV

      - name: 'Build and push Docker image'
        run: |
          docker build src -f src/Wpm.Management.Api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{env.DATE}}-${{github.run_number}}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{env.DATE}}-${{github.run_number}}